### ISSUE TITLE
Feedback documentatie

### ISSUE THREAD

**Issue by roberrrt-s** [ManoukK/functional-programming#14]
Hi Manouk,

Je wiki leest goed weg, ik krijg een goed beeld van je proces en wat je geleerd hebt. In je readme zou ik, naast de query die je binnenhaalt bij data, ook graag een korte uitleg willen welke data je dan terugkrijgt en waarom je deze data krijgt. Bij features kun je dan een een kort lijstje van de toepassingen die je met deze data gaat maken / hebt gemaakt uitlichten.

Vergeet tenslotte niet om inhoudelijk te reageren op issues, je kunt issues closen door ze te te benoemen in een commit, maar beter is om eerst te reageren met wat je precies hebt gedaan om ze op te lossen, en daarna handmatig, of eventueel met een commit te closen.

Zie:
https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by ManoukK** [comment]
Dankje voor je feedback! 

Ik heb nu duidelijk in mijn readme opgeschreven met wat voor query ik werk en wat ik er mee doe (dit staat onder data).

Verder heb ik nog bij de features punten benoemt die ik met een checkbox kan afvinken.

Ook ben ik nu de laatste issues aan het sluiten. Ik heb bij alle issues die ik net heb afgesloten duidelijke comments achtergelaten.
