### ISSUE TITLE
Clean de data van museum nog

### ISSUE THREAD

**Issue by RoyCsuka** [ManoukK/functional-programming#7]
JS in de folder docs, is ok! Clean de data ook nog voor het museum. Wat je nu al af hebt is heel netjes gedaan dus houd dat vast. Met netjes bedoel ik:
- Ik snap de code flow
- Ik zie je verbeteringen
- Het is functioneel, consistent en herbruikbaar

**Comment by ManoukK** [comment]
de data die ik binnen haal hoeft niet erg opgeschoond te worden maar er staat nu wel in mijn readme wat ik opschoon (dat is wel heel weinig) en hoe ik het omzet in een andere array
